export function getChatCopy(language = 'en') {
  if (language === 'de') {
    return {
      title: 'Internal Chat',
      subtitle: 'Echtzeitkommunikation, Direktnachrichten, General-Raum und sichere Anhaenge innerhalb des Systems.',
      statusConnected: 'Echtzeit verbunden',
      statusReconnecting: 'Verbindung wird wiederhergestellt',
      statusError: 'Verbindungsproblem',
      statusConnecting: 'Verbinden',
      roomsTitle: 'Chats',
      roomsSubtitle: 'General und private Unterhaltungen der Mitarbeitenden.',
      newChat: 'Neuer Chat',
      roomsEmpty: 'Noch keine Chat-Raeume verfuegbar. General erscheint, sobald die Chat-Mitgliedschaften synchronisiert sind.',
      roomsLoading: 'Chat-Raeume werden geladen...',
      noMessagesSelected: 'Waehlen Sie links General oder einen privaten Chat aus, um zu schreiben.',
      generalDescription: 'Gemeinsamer Raum fuer alle registrierten Portalbenutzer',
      directParticipants: 'Teilnehmer',
      messagesLoading: 'Nachrichten werden geladen...',
      loadOlder: 'Aeltere Nachrichten laden',
      loadingOlder: 'Aeltere Nachrichten werden geladen...',
      generalEmpty: 'General ist bereit. Senden Sie die erste Nachricht in den gemeinsamen Raum.',
      directEmpty: 'Dieser Direktchat ist bereit. Sie koennen jetzt die erste Nachricht senden.',
      you: 'Sie',
      attachmentLabel: 'Anhang',
      download: 'Herunterladen',
      composerGeneralPlaceholder: 'Schreiben Sie eine Nachricht an den General-Raum...',
      composerPlaceholder: 'Schreiben Sie eine Nachricht...',
      attachFile: 'Datei anhaengen',
      noFile: 'Keine Datei ausgewaehlt',
      send: 'Senden',
      sending: 'Wird gesendet...',
      directDialogTitle: 'Direktchat starten',
      directDialogSubtitle: 'Hier werden alle registrierten Portalbenutzer mit Vorname, Nachname und Profilbild angezeigt, sofern vorhanden.',
      close: 'Schliessen',
      cancel: 'Abbrechen',
      searchPlaceholder: 'Nach Name oder E-Mail suchen',
      usersLoading: 'Benutzer werden geladen...',
      usersEmpty: 'Noch keine registrierten Benutzer fuer einen Direktchat verfuegbar.',
      usersSearchEmpty: 'Keine Benutzer passen zur aktuellen Suche.',
      open: 'Oeffnen',
      openShort: 'Oeffnen',
      roomUnavailable: 'Die Chat-Raeume konnten gerade nicht geladen werden.',
      usersUnavailable: 'Die Benutzer konnten gerade nicht geladen werden.',
      messagesUnavailable: 'Die Nachrichten konnten gerade nicht geladen werden.',
      sendUnavailable: 'Die Nachricht konnte nicht gesendet werden.',
      userNoEmail: 'Keine E-Mail',
      noMessagesYet: 'Noch keine Nachrichten',
      generalHint: 'General-Raum fuer alle Mitarbeitenden',
    };
  }

  return {
    title: 'Internal Chat',
    subtitle: 'Realtime communication, direct messages, General room and secure attachments inside the system.',
    statusConnected: 'Realtime connected',
    statusReconnecting: 'Reconnecting',
    statusError: 'Connection issue',
    statusConnecting: 'Connecting',
    roomsTitle: 'Chats',
    roomsSubtitle: 'General and private employee conversations.',
    newChat: 'New chat',
    roomsEmpty: 'No chat rooms available yet. General will appear as soon as the chat membership is synchronized.',
    roomsLoading: 'Loading chat rooms...',
    noMessagesSelected: 'Select General or a private chat on the left to start messaging.',
    generalDescription: 'Shared room for all registered portal users',
    directParticipants: 'Participants',
    messagesLoading: 'Loading messages...',
    loadOlder: 'Load older messages',
    loadingOlder: 'Loading older messages...',
    generalEmpty: 'General is ready. Send the first message to the shared room.',
    directEmpty: 'This direct chat is ready. You can send the first message now.',
    you: 'You',
    attachmentLabel: 'attachment',
    download: 'Download',
    composerGeneralPlaceholder: 'Write a message to the General room...',
    composerPlaceholder: 'Write a message...',
    attachFile: 'Attach file',
    noFile: 'No file selected',
    send: 'Send',
    sending: 'Sending...',
    directDialogTitle: 'Start direct chat',
    directDialogSubtitle: 'All registered portal users are listed here with first name, last name and profile photo when available.',
    close: 'Close',
    cancel: 'Cancel',
    searchPlaceholder: 'Search by name or e-mail',
    usersLoading: 'Loading users...',
    usersEmpty: 'No registered users are available for direct chat yet.',
    usersSearchEmpty: 'No users match your current search.',
    open: 'Open',
    openShort: 'Open',
    roomUnavailable: 'Chat rooms could not be loaded right now.',
    usersUnavailable: 'Users could not be loaded right now.',
    messagesUnavailable: 'Messages could not be loaded right now.',
    sendUnavailable: 'Message could not be sent.',
    userNoEmail: 'No e-mail',
    noMessagesYet: 'No messages yet',
    generalHint: 'General room for all employees',
  };
}

export default getChatCopy;
