export const sidebarMenuItems = [
  {
    id: 'employees',
    type: 'group',
    label: 'Employees',
    icon: 'users',
    items: [
      {
        id: 'employee-list',
        type: 'item',
        path: '/kenjo-sync',
        labelKey: 'nav.employeeList',
        matchPatterns: ['/kenjo-sync', '/employee*'],
      },
      {
        id: 'personalfragebogen',
        type: 'item',
        path: '/personal-fragebogen-review',
        label: 'Personalfragebogen',
        permissionCode: 'page_employees',
        matchPatterns: ['/personal-fragebogen-review', '/personal-fragebogen-notifications'],
      },
    ],
  },
  {
    id: 'fleet',
    type: 'group',
    label: 'Fleet',
    icon: 'fleet',
    items: [
      {
        id: 'cars',
        type: 'item',
        path: '/cars',
        labelKey: 'nav.cars',
        matchPatterns: ['/cars'],
      },
      {
        id: 'car-planning',
        type: 'item',
        path: '/car-planning',
        labelKey: 'nav.carPlanning',
        matchPatterns: ['/car-planning'],
      },
      {
        id: 'damages',
        type: 'item',
        path: '/damages',
        labelKey: 'nav.damages',
        permissionCode: 'page_damages',
        matchPatterns: ['/damages'],
      },
      {
        id: 'schadenmeldung',
        type: 'item',
        path: '/schadenmeldung-review',
        label: 'Schadensmeldung',
        permissionCode: 'page_damages',
        matchPatterns: ['/schadenmeldung-review'],
      },
      {
        id: 'insurance',
        type: 'item',
        path: '/insurance',
        labelKey: 'nav.insurance',
        permissionCode: 'page_insurance',
        matchPatterns: ['/insurance*'],
      },
      {
        id: 'pave',
        type: 'item',
        path: '/pave',
        labelKey: 'nav.pave',
        matchPatterns: ['/pave*'],
      },
    ],
  },
  {
    id: 'salaries',
    type: 'group',
    label: 'Salaries',
    icon: 'wallet',
    items: [
      {
        id: 'payroll',
        type: 'item',
        path: '/payroll',
        labelKey: 'nav.payroll',
        permissionCode: 'page_payroll',
        matchPatterns: ['/payroll'],
      },
      {
        id: 'sync-kenjo',
        type: 'item',
        path: '/sync-kenjo',
        labelKey: 'nav.syncKenjo',
        permissionCode: 'page_sync_kenjo',
        matchPatterns: ['/sync-kenjo'],
      },
      {
        id: 'finance',
        type: 'item',
        path: '/finance',
        labelKey: 'nav.finance',
        permissionCode: 'page_finance',
        matchPatterns: ['/finance'],
      },
      {
        id: 'fines',
        type: 'item',
        path: '/fines',
        labelKey: 'nav.fines',
        permissionCode: 'page_fines',
        matchPatterns: ['/fines'],
      },
      {
        id: 'gift-cards',
        type: 'item',
        path: '/gift-cards',
        labelKey: 'nav.giftCards',
        permissionCode: 'page_gift_cards',
        matchPatterns: ['/gift-cards'],
      },
    ],
  },
  {
    id: 'calendar',
    type: 'item',
    path: '/kenjo-calendar',
    labelKey: 'nav.calendar',
    icon: 'calendar',
    matchPatterns: ['/kenjo-calendar'],
  },
  {
    id: 'documents-reports',
    type: 'group',
    label: 'Documents & Reports',
    icon: 'files',
    items: [
      {
        id: 'cortex-uploads',
        type: 'item',
        path: '/calendar',
        labelKey: 'nav.cortexUploads',
        matchPatterns: ['/calendar'],
      },
      {
        id: 'scorecard-uploads',
        type: 'item',
        path: '/scorecard-uploads',
        labelKey: 'nav.scorecardUploads',
        matchPatterns: ['/scorecard-uploads'],
      },
      {
        id: 'create-document',
        type: 'item',
        path: '/create-document',
        labelKey: 'nav.createDocument',
        matchPatterns: ['/create-document'],
      },
    ],
  },
  {
    id: 'o2-telefonica',
    type: 'item',
    path: '/o2-telefonica',
    labelKey: 'nav.o2Telefonica',
    icon: 'phone',
    matchPatterns: ['/o2-telefonica'],
  },
];
