export const fleetRentalsCopy = {
  en: {
    selfVehicles: 'Self Source vehicles this month', rentalVehicles: 'Rental vehicles this month',
    totalCost: 'Rental cost total (gross)', totalCostHelp: 'All rental periods · current filters · excludes extra mileage', missingTotalCosts: 'vehicles with incomplete costs',
    businessDays: 'Business days', businessDaysHelp: 'Monday–Saturday, excluding Sundays and statewide Bavarian public holidays. Both rental dates included. Local holidays on 8 and 15 August are not applied.',
    drivenRoutes: 'Driven Roots', noRouteData: 'No uploaded route data', routesNote: '— = no uploaded route data. Counts cover the entire fleet.', routesError: 'Unable to load driven routes. Please refresh.', lmrVehicles: 'LMR vehicles this month', lmrSeparate: 'Separate payment model',
    monthlyRate: 'Monthly rate (€ gross)', monthlyKm: 'Included km / month', totalPricing: 'Total Pricing (€ gross)', totalKm: 'Included kilometres · total', linkedPricingHelp: 'Enter a daily, monthly or total value. The other values update automatically. One month = 30 days. Date changes preserve the last value entered. Daily equivalents are rounded; contract totals stay exact. Total Pricing excludes extra mileage.',
    addDamage: 'Add Damage', uploadProtocol: 'Übergabeprotokoll hochladen', documents: 'Handover protocols, photos & documents', addAttachments: 'Add photos / documents', documentsHelp: 'Multiple files are supported, up to 15 MB each. Uploads are saved immediately to this vehicle, independently of Save Changes.', fileSize: 'Choose a non-empty file up to 15 MB.', loadingDocuments: 'Loading…', uploading: 'Uploading files…', uploaded: '{n} files uploaded.', noDocuments: 'No documents added yet.', viewDocument: 'View / download', fileUnavailable: 'File unavailable', download: 'Download', downloadToView: 'Download this document to open it in the appropriate application.', unsavedNavigation: 'Leave for Add Damage? Unsaved rental changes will be lost. Uploaded files are already saved.',
    financialResult: 'Income & expenses', net: 'Net', gross: 'Gross', weReceive: 'We receive', wePay: 'We pay', resultDifference: 'Difference', netPerDay: 'net / day', noServiceType: 'Service Type not set', unknownService: 'No income rate is configured for this Service Type.', vatHelp: 'VAT 19%. Rental prices entered include VAT. Income is calculated for every rental day.', estimatedResult: 'Estimate based on base rental. Final mileage charges are not yet included.',
    title: 'Rental calendar', subtitle: 'Rental periods, costs and mileage in one place.',
    search: 'Search plate, vehicle, station…', allSources: 'All sources', allStatus: 'All periods',
    active: 'Active', upcoming: 'Upcoming', ended: 'Ended', missing: 'Dates needed',
    today: 'Today', previous: 'Previous month', next: 'Next month', refresh: 'Refresh',
    vehicles: 'Vehicles this month', monthlyCost: 'Rental cost this month (gross)', ending: 'Ending in 7 days',
    incomplete: 'Missing dates', vehicle: 'Vehicle', loading: 'Loading rental calendar…',
    empty: 'No vehicles match these filters.', outside: 'Outside this month', setup: 'Set rental dates',
    legend: 'Select a vehicle or its rental bar to edit.', details: 'Rental details',
    period: 'Rental period', from: 'Active from', to: 'Active to', inclusive: 'Pickup and return dates both count as rental days. Dates are shared with Car Planning.',
    pricing: 'Pricing & allowance', rate: 'Daily rate (€ gross)', dailyKm: 'Included km / day', extraRate: 'Extra kilometre (€ gross / km)',
    odometer: 'Odometer', startKm: 'Initial reading (km)', endKm: 'Final reading (km)',
    currentKm: 'Latest mileage in Cars', notes: 'Notes', notesPlaceholder: 'Supplier, contract number, return instructions…',
    summary: 'Rental calculation', days: 'Rental days', base: 'Base rental', allowance: 'Included distance',
    driven: 'Distance driven', difference: 'Mileage balance', extra: 'Extra mileage cost', total: 'Total rental cost',
    balanceHelp: 'Positive = over allowance. Negative = unused kilometres; no refund is assumed.',
    pending: 'Enter final mileage to calculate the final total.', unpriced: 'Enter the missing rates to complete the calculation.',
    cancel: 'Cancel', save: 'Save changes', saving: 'Saving…', close: 'Close', saved: 'Rental details saved.',
    errorDates: 'Enter valid dates. End date must be on or after start date.',
    errorOdometer: 'Enter an initial reading; final mileage cannot be lower than initial mileage.',
    knownOnly: 'Rental / Self source · excludes extra mileage', missingRates: 'vehicles without a daily rate',
    currency: 'All amounts in EUR, using the rates entered.', retry: 'Try again',
  },
  de: {
    selfVehicles: 'Self Source-Fahrzeuge diesen Monat', rentalVehicles: 'Rental-Fahrzeuge diesen Monat',
    totalCost: 'Mietkosten gesamt (brutto)', totalCostHelp: 'Alle Mietzeiträume · aktuelle Filter · ohne Mehrkilometer', missingTotalCosts: 'Fahrzeuge mit unvollständigen Kosten',
    businessDays: 'Arbeitstage', businessDaysHelp: 'Montag–Samstag, ohne Sonntage und landesweite Feiertage in Bayern. Mietbeginn und Mietende zählen mit. Lokale Feiertage am 8. und 15. August sind nicht berücksichtigt.',
    drivenRoutes: 'Driven Roots', noRouteData: 'Keine hochgeladenen Routendaten', routesNote: '— = keine hochgeladenen Routendaten. Anzahl für die gesamte Flotte.', routesError: 'Routendaten konnten nicht geladen werden. Bitte aktualisieren.', lmrVehicles: 'LMR-Fahrzeuge diesen Monat', lmrSeparate: 'Separates Abrechnungsmodell',
    monthlyRate: 'Monatstarif (€ brutto)', monthlyKm: 'Freikilometer / Monat', totalPricing: 'Gesamtpreis (€ brutto)', totalKm: 'Freikilometer · gesamt', linkedPricingHelp: 'Tages-, Monats- oder Gesamtwert eingeben. Die anderen Werte werden automatisch berechnet. Ein Monat = 30 Tage. Bei Datumsänderungen bleibt der zuletzt eingegebene Wert erhalten. Tageswerte werden gerundet; Vertragssummen bleiben exakt. Gesamtpreis ohne Mehrkilometer.',
    addDamage: 'Schaden hinzufügen', uploadProtocol: 'Übergabeprotokoll hochladen', documents: 'Übergabeprotokolle, Fotos & Dokumente', addAttachments: 'Fotos / Dokumente hinzufügen', documentsHelp: 'Mehrere Dateien möglich, jeweils bis 15 MB. Uploads werden sofort zum Fahrzeug gespeichert, unabhängig von Änderungen speichern.', fileSize: 'Nicht leere Datei bis 15 MB auswählen.', loadingDocuments: 'Laden…', uploading: 'Dateien werden hochgeladen…', uploaded: '{n} Dateien hochgeladen.', noDocuments: 'Noch keine Dokumente vorhanden.', viewDocument: 'Ansehen / herunterladen', fileUnavailable: 'Datei nicht verfügbar', download: 'Herunterladen', downloadToView: 'Datei herunterladen und mit der passenden Anwendung öffnen.', unsavedNavigation: 'Zur Schadenserfassung wechseln? Ungespeicherte Mietänderungen gehen verloren. Hochgeladene Dateien sind bereits gespeichert.',
    financialResult: 'Einnahmen & Ausgaben', net: 'Netto', gross: 'Brutto', weReceive: 'Wir erhalten', wePay: 'Wir zahlen', resultDifference: 'Differenz', netPerDay: 'netto / Tag', noServiceType: 'Service Type fehlt', unknownService: 'Für diesen Service Type ist kein Einnahmetarif hinterlegt.', vatHelp: 'MwSt. 19%. Eingegebene Mietpreise sind brutto. Einnahmen werden für jeden Miettag berechnet.', estimatedResult: 'Schätzung auf Basis der Grundmiete. Endgültige Mehrkilometerkosten sind noch nicht enthalten.',
    title: 'Mietkalender', subtitle: 'Mietzeiträume, Kosten und Kilometer auf einen Blick.',
    search: 'Kennzeichen, Fahrzeug, Station suchen…', allSources: 'Alle Quellen', allStatus: 'Alle Zeiträume',
    active: 'Aktiv', upcoming: 'Geplant', ended: 'Beendet', missing: 'Zeitraum fehlt',
    today: 'Heute', previous: 'Vorheriger Monat', next: 'Nächster Monat', refresh: 'Aktualisieren',
    vehicles: 'Fahrzeuge diesen Monat', monthlyCost: 'Mietkosten diesen Monat (brutto)', ending: 'Endet in 7 Tagen',
    incomplete: 'Fehlende Zeiträume', vehicle: 'Fahrzeug', loading: 'Mietkalender wird geladen…',
    empty: 'Keine Fahrzeuge für diese Filter.', outside: 'Außerhalb dieses Monats', setup: 'Mietzeitraum festlegen',
    legend: 'Fahrzeug oder Mietbalken zum Bearbeiten auswählen.', details: 'Mietdetails',
    period: 'Mietzeitraum', from: 'Aktiv ab', to: 'Aktiv bis', inclusive: 'Abhol- und Rückgabetag zählen als Miettage. Die Daten werden mit Car Planning geteilt.',
    pricing: 'Tarif & Freikilometer', rate: 'Tagestarif (€ brutto)', dailyKm: 'Freikilometer / Tag', extraRate: 'Mehrkilometer (€ brutto / km)',
    odometer: 'Kilometerstand', startKm: 'Anfangsstand (km)', endKm: 'Endstand (km)',
    currentKm: 'Letzter Kilometerstand in Cars', notes: 'Notizen', notesPlaceholder: 'Vermieter, Vertragsnummer, Rückgabehinweise…',
    summary: 'Mietberechnung', days: 'Miettage', base: 'Grundmiete', allowance: 'Freikilometer gesamt',
    driven: 'Gefahrene Strecke', difference: 'Kilometerbilanz', extra: 'Mehrkilometerkosten', total: 'Gesamte Mietkosten',
    balanceHelp: 'Positiv = Mehrkilometer. Negativ = ungenutzte Kilometer; keine Erstattung angenommen.',
    pending: 'Endstand eingeben, um die Gesamtkosten zu berechnen.', unpriced: 'Fehlende Tarife für die Berechnung eingeben.',
    cancel: 'Abbrechen', save: 'Änderungen speichern', saving: 'Speichern…', close: 'Schließen', saved: 'Mietdetails gespeichert.',
    errorDates: 'Gültigen Zeitraum eingeben. Das Enddatum darf nicht vor dem Startdatum liegen.',
    errorOdometer: 'Anfangsstand eingeben; der Endstand darf nicht darunter liegen.',
    knownOnly: 'Rental / Self source · ohne Mehrkilometer', missingRates: 'Fahrzeuge ohne Tagestarif',
    currency: 'Alle Beträge in EUR anhand der eingegebenen Tarife.', retry: 'Erneut versuchen',
  },
};
