export const fleetRentalsCopy = {
  en: {
    title: 'Rental calendar', subtitle: 'Rental periods, costs and mileage in one place.',
    search: 'Search plate, vehicle, station…', allSources: 'All sources', allStatus: 'All periods',
    active: 'Active', upcoming: 'Upcoming', ended: 'Ended', missing: 'Dates needed',
    today: 'Today', previous: 'Previous month', next: 'Next month', refresh: 'Refresh',
    vehicles: 'Vehicles this month', monthlyCost: 'Rental cost this month', ending: 'Ending in 7 days',
    incomplete: 'Missing dates', vehicle: 'Vehicle', loading: 'Loading rental calendar…',
    empty: 'No vehicles match these filters.', outside: 'Outside this month', setup: 'Set rental dates',
    legend: 'Select a vehicle or its rental bar to edit.', details: 'Rental details',
    period: 'Rental period', from: 'Active from', to: 'Active to', inclusive: 'Pickup and return dates both count as rental days. Dates are shared with Car Planning.',
    pricing: 'Pricing & allowance', rate: 'Daily rate (€)', dailyKm: 'Included km / day', extraRate: 'Extra kilometre (€ / km)',
    odometer: 'Odometer', startKm: 'Initial reading (km)', endKm: 'Final reading (km)',
    currentKm: 'Latest mileage in Cars', notes: 'Notes', notesPlaceholder: 'Supplier, contract number, return instructions…',
    summary: 'Rental calculation', days: 'Rental days', base: 'Base rental', allowance: 'Included distance',
    driven: 'Distance driven', difference: 'Mileage balance', extra: 'Extra mileage cost', total: 'Total rental cost',
    balanceHelp: 'Positive = over allowance. Negative = unused kilometres; no refund is assumed.',
    pending: 'Enter final mileage to calculate the final total.', unpriced: 'Enter the missing rates to complete the calculation.',
    cancel: 'Cancel', save: 'Save changes', saving: 'Saving…', close: 'Close', saved: 'Rental details saved.',
    errorDates: 'Enter valid dates. End date must be on or after start date.',
    errorOdometer: 'Enter an initial reading; final mileage cannot be lower than initial mileage.',
    knownOnly: 'Known daily rates · excludes extra mileage', missingRates: 'vehicles without a daily rate',
    currency: 'All amounts in EUR, using the rates entered.', retry: 'Try again',
  },
  de: {
    title: 'Mietkalender', subtitle: 'Mietzeiträume, Kosten und Kilometer auf einen Blick.',
    search: 'Kennzeichen, Fahrzeug, Station suchen…', allSources: 'Alle Quellen', allStatus: 'Alle Zeiträume',
    active: 'Aktiv', upcoming: 'Geplant', ended: 'Beendet', missing: 'Zeitraum fehlt',
    today: 'Heute', previous: 'Vorheriger Monat', next: 'Nächster Monat', refresh: 'Aktualisieren',
    vehicles: 'Fahrzeuge diesen Monat', monthlyCost: 'Mietkosten diesen Monat', ending: 'Endet in 7 Tagen',
    incomplete: 'Fehlende Zeiträume', vehicle: 'Fahrzeug', loading: 'Mietkalender wird geladen…',
    empty: 'Keine Fahrzeuge für diese Filter.', outside: 'Außerhalb dieses Monats', setup: 'Mietzeitraum festlegen',
    legend: 'Fahrzeug oder Mietbalken zum Bearbeiten auswählen.', details: 'Mietdetails',
    period: 'Mietzeitraum', from: 'Aktiv ab', to: 'Aktiv bis', inclusive: 'Abhol- und Rückgabetag zählen als Miettage. Die Daten werden mit Car Planning geteilt.',
    pricing: 'Tarif & Freikilometer', rate: 'Tagestarif (€)', dailyKm: 'Freikilometer / Tag', extraRate: 'Mehrkilometer (€ / km)',
    odometer: 'Kilometerstand', startKm: 'Anfangsstand (km)', endKm: 'Endstand (km)',
    currentKm: 'Letzter Kilometerstand in Cars', notes: 'Notizen', notesPlaceholder: 'Vermieter, Vertragsnummer, Rückgabehinweise…',
    summary: 'Mietberechnung', days: 'Miettage', base: 'Grundmiete', allowance: 'Freikilometer gesamt',
    driven: 'Gefahrene Strecke', difference: 'Kilometerbilanz', extra: 'Mehrkilometerkosten', total: 'Gesamte Mietkosten',
    balanceHelp: 'Positiv = Mehrkilometer. Negativ = ungenutzte Kilometer; keine Erstattung angenommen.',
    pending: 'Endstand eingeben, um die Gesamtkosten zu berechnen.', unpriced: 'Fehlende Tarife für die Berechnung eingeben.',
    cancel: 'Abbrechen', save: 'Änderungen speichern', saving: 'Speichern…', close: 'Schließen', saved: 'Mietdetails gespeichert.',
    errorDates: 'Gültigen Zeitraum eingeben. Das Enddatum darf nicht vor dem Startdatum liegen.',
    errorOdometer: 'Anfangsstand eingeben; der Endstand darf nicht darunter liegen.',
    knownOnly: 'Bekannte Tagestarife · ohne Mehrkilometer', missingRates: 'Fahrzeuge ohne Tagestarif',
    currency: 'Alle Beträge in EUR anhand der eingegebenen Tarife.', retry: 'Erneut versuchen',
  },
};
